version: '3.8'

services:
  react-app:
    build:
      context: ./ # Path to the first React app directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
    command: npm start